### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by bartolom** [danielshaya/FileSystemMap#1]
Dear danielshaya

Your utility looks lke a nice tool to make unit test that interact with the file system more concise. It would be nice to know which open source license this code ist. A liberal license like Apache 2.0 or MIT or Public Domain would be appreciated.

**Comment by danielshaya** [comment]
Good idea.
Please feel free to fork and submit a pull request with Apache 2.0.
I'll pull the request.

**Comment by bartolom** [comment]
Closing this old issue, as the pull request was done successfully in Feb 2016
